name: 回饋 (Feedback)
description: 分享你的回饋以協助改進 AgenticUsage (Share your feedback to help improve AgenticUsage)
title: "[回饋 (Feedback)] "
body:
  - type: markdown
    attributes:
      value: |
        感謝分享你的回饋！請填寫以下資訊。 (Thanks for sharing your feedback! Please fill out the details below.)
  - type: textarea
    id: summary
    attributes:
      label: 回饋摘要 (Feedback summary)
      description: 你的回饋是什麼？ (What is your feedback?)
      placeholder: 請告訴我們你的想法。 (Tell us what you think.)
    validations:
      required: true
  - type: dropdown
    id: product
    attributes:
      label: 使用介面 (App or CLI)
      description: 你是使用 App 還是 CLI？ (Are you using the App or CLI?)
      options:
        - App
        - CLI
    validations:
      required: true
  - type: input
    id: app_cli_version
    attributes:
      label: App / CLI 版本 (App / CLI version)
      description: 請填寫你目前使用的版本。 (Please provide the version you are using.)
      placeholder: 例如：1.2.3 (e.g., 1.2.3)
    validations:
      required: true
  - type: input
    id: os_version
    attributes:
      label: 作業系統版本 (Operating system version)
      description: 請填寫作業系統與版本。 (Please provide your operating system and version.)
      placeholder: 例如：macOS 15.3 (e.g., macOS 15.3)
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: 補充資訊 (Additional details)
      description: 是否有任何背景、範例或建議？ (Any context, examples, or suggestions?)
      placeholder: 請在此補充其他資訊。 (Add any extra information here.)
    validations:
      required: false
